// <auto-generated />
using System;
using FGS.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FGS.DAL.Context.Migrations
{
    [DbContext(typeof(FgsViewModelContext))]
    partial class FgsViewModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FGS.DAL.ViewModel.Entities.EventSourceStreamTracker", b =>
                {
                    b.Property<int>("StreamTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StreamTypeId"));

                    b.Property<decimal>("CommitPosition")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("PreparePosition")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("StreamTypeId");

                    b.ToTable("EventSourceStreamTracker", (string)null);
                });

            modelBuilder.Entity("FGS.Domain.FgsLobby.Entities.ConnectionTrackerEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayerRole")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("LobbyId");

                    b.ToTable("ConnectionTracker", (string)null);
                });

            modelBuilder.Entity("FGS.Domain.FgsLobby.Entities.LobbyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("ConnectedUsers")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PlayersCount")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Lobby", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
